- futurenhs.app/components/Dialog/component.test.tsx
- futurenhs.app/components/DynamicListContainer/component.test.tsx
- futurenhs.app/components/GroupPageHeader/component.test.tsx
- futurenhs.app/components/_formComponents/GroupContainer/component.test.tsx
- futurenhs.app/components/_pageTemplates/AdminHomeTemplate/component.test.tsx
- futurenhs.app/components/_pageTemplates/AdminUsersTemplate/component.test.tsx
- futurenhs.app/components/_pageTemplates/SiteUserTemplate/component.test.tsx
- futurenhs.app/helpers/formatters/capitalise/formatter.test.ts
- futurenhs.app/helpers/formatters/dateTime/index.ts
- futurenhs.app/helpers/validators/email/validator.test.ts
- futurenhs.app/hofs/withForms/hof.test.ts
- futurenhs.app/hofs/withGroup/hof.test.ts
- futurenhs.app/jest-mocks/handlers.tsx
- futurenhs.app/jest.config.js
- futurenhs.app/jest.setup.ts
- futurenhs.app/pages/admin/groups/page.text.tsx
- futurenhs.app/pages/admin/page.text.tsx
- futurenhs.app/pages/admin/users/page.text.tsx
- futurenhs.app/pages/groups/[groupId]/files/[fileId]/detail/page.test.tsx
- futurenhs.app/pages/groups/[groupId]/files/[fileId]/index.page.tsx
- futurenhs.app/pages/groups/[groupId]/files/[fileId]/page.test.tsx
- futurenhs.app/pages/groups/[groupId]/folders/[folderId]/page.test.tsx
- futurenhs.app/pages/groups/[groupId]/folders/page.test.tsx
- futurenhs.app/pages/groups/[groupId]/page.test.tsx
- futurenhs.app/pages/groups/page.test.tsx
- futurenhs.app/services/getGroup/index.ts
- futurenhs.app/services/getSearchResults/service.test.ts
Migrates Nuh's tests, adds additional unit tests, adds test env variables to jest config
> Unit tests

- futurenhs.app/next.config.js
- futurenhs.app/pages/groups/[groupId]/folders/[folderId]/update/index.page.tsx
[*] Fixes blobtest image url error in local dev
> [*] Fixes folder data not being prepopulated correctly on edit

- futurenhs.content.api/Umbraco9ContentApi.Models/TextBlock.generated.cs
- futurenhs.content.api/Umbraco9ContentApi.Umbraco/uSync/v9/Content/text-block-placeholder.config
- futurenhs.content.api/Umbraco9ContentApi.Umbraco/uSync/v9/ContentTypes/blocksfolder.config
- futurenhs.content.api/Umbraco9ContentApi.Umbraco/uSync/v9/ContentTypes/textblock.config
- futurenhs.content.api/Umbraco9ContentApi.Umbraco/uSync/v9/ContentTypes/textimageblock.config
- allows text block placeholder to be available through content api
> - add text block

- futurenhs.app/components/Form/index.tsx
- futurenhs.app/components/_pageTemplates/GroupDiscussionTemplate/index.tsx
- futurenhs.app/components/_pageTemplates/GroupMemberTemplate/index.tsx
- futurenhs.app/constants/forms.ts
- futurenhs.app/form-configs/update-group-member.ts
- futurenhs.app/pages/groups/[groupId]/members/[memberId]/index.page.tsx
- awaiting completion of API endpoints before wiring up
> [*] Progresses group member edit UI

- futurenhs.api/FutureNHS.Api/Models/Comment/Comment.cs
- futurenhs.api/FutureNHS.Api/Models/Discussion/Discussion.cs
- futurenhs.api/FutureNHS.Api/Models/Folder/Folder.cs
- futurenhs.api/FutureNHS.Api/Services/CommentService.cs
- futurenhs.api/FutureNHS.Api/Services/DiscussionService.cs
- futurenhs.api/FutureNHS.Api/Services/FileService.cs
- futurenhs.api/FutureNHS.Api/Services/GroupService.cs
- futurenhs.api/FutureNHS.Api/Services/Validation/CommentValidator.cs
- futurenhs.api/FutureNHS.Api/Services/Validation/DiscussionValidator.cs
- futurenhs.api/FutureNHS.Api/Services/Validation/FileValidator.cs
- futurenhs.api/FutureNHS.Api/Services/Validation/FolderValidator.cs
- futurenhs.api/FutureNHS.Api/Services/Validation/GroupValidator.cs
- futurenhs.api/FutureNHS.Api/Services/Validation/ImageValidator.cs
[+] Adds validators for comment, discussion, folder and file
> [Api] Adds validation to endpoints

- MVCForum/azure-pipelines.yml
> Set up CI with Azure Pipelines

- futurenhs.api/FutureNHS.Api/Services/GroupService.cs
[*] Null check for when image isn't uploaded
> [Api] - Fixes validation for image

- futurenhs.api/FutureNHS.Api/DataAccess/Database/Write/FolderCommand.cs
- futurenhs.api/FutureNHS.Api/DataAccess/Database/Write/Interfaces/IFolderCommand.cs
- futurenhs.api/FutureNHS.Api/Services/Validation/CommentValidator.cs
- futurenhs.api/FutureNHS.Api/Services/Validation/DiscussionValidator.cs
- futurenhs.api/FutureNHS.Api/Services/Validation/FileValidator.cs
- futurenhs.api/FutureNHS.Api/Services/Validation/FolderValidator.cs
- futurenhs.api/FutureNHS.Api/Services/Validation/GroupValidator.cs
[*] Folder now ignores its own name
[*] Updates validation messages to match frontend
> [Api] Bug 94385 - Fixes duplicate folder validation

- futurenhs.automation/features/userAccess.feature
- futurenhs.automation/pageObjects/contentCard.js
- futurenhs.automation/pageObjects/filesPage.js
- futurenhs.automation/pageObjects/formPage.js
- futurenhs.automation/pageObjects/genericPage.js
- futurenhs.automation/pageObjects/search.js
- futurenhs.automation/stepDefinitions/ThenSteps.js
[+] adding annotation to test functions
[*] refactored new tab validation for reuse if needed
> Automation Documentation

- futurenhs.api/FutureNHS.Api/Exceptions/ValidationException.cs
- futurenhs.api/FutureNHS.Api/Services/GroupService.cs
[*] Fixes group valdation when incoming name value is empty
> [Api] Fixes group validation with JS off

- futurenhs.app/components/_pageTemplates/AdminGroupsTemplate/index.tsx
- futurenhs.app/components/_pageTemplates/AdminUsersInviteTemplate/index.tsx
- futurenhs.app/pages/admin/groups/index.page.tsx
- futurenhs.app/pages/admin/users/index.page.tsx
[*] Updates column widths in admin groups tables
> [*] Updates items per page on admin dashboard tables to 20

- futurenhs.app/components/ErrorSummary/index.tsx
- futurenhs.app/components/Form/index.tsx
- futurenhs.app/components/_formComponents/AutoComplete/index.tsx
- futurenhs.app/components/_formComponents/AutoComplete/interfaces.ts
- futurenhs.app/form-configs/create-group.ts
- futurenhs.app/types/form.d.ts
[*] Updates error summary to link to first radio option (if existing)
> [*] Progresses AutoComplete component

- futurenhs.app/next.config.js
- futurenhs.app/services/getGroups/index.ts
[*] Updates group image alt tag
> [*] Updates next.config with new image domain

- futurenhs.app/server.js
@simplybenuk do these origins match what you're seeing in your CSP errors?
> [*] Updates CSP to match tags being employed in GTM in production

- futurenhs.api/FutureNHS.Api/DataAccess/DTOs/GroupDto.cs
- futurenhs.api/FutureNHS.Api/Exceptions/ValidationException.cs
- futurenhs.api/FutureNHS.Api/Services/Validation/FileValidator.cs
[*] Updates file validation to check for file size
> [Api] Fixes file validation when non-js 

- futurenhs.app/components/_formComponents/AutoComplete/index.tsx
- futurenhs.app/components/_formComponents/AutoComplete/interfaces.ts
- futurenhs.app/services/getSiteUsersByTerm/index.ts
[*] Makes autoComplete min characters configurable and defaults to 2
> [*] Connects getSiteUsersByTerm service to API

- futurenhs.automation/sqlQueries/dataReset.sql
- futurenhs.automation/sqlQueries/fullAutomationDataTeardown.sql
- futurenhs.data/FutureNHS.Data.FutureNHS/Data/AutomationTeardownData.sql
[*] refactored dataReset and dataTeardown scripts removing un-needed scripts, and hardcoded values for more generic Select statements to improve stability
> Automation SQL Refactor

- futurenhs.api/FutureNHS.Api/DataAccess/DTOs/GroupDto.cs
- futurenhs.api/FutureNHS.Api/DataAccess/Database/Read/GroupDataProvider.cs
- futurenhs.api/FutureNHS.Api/DataAccess/Database/Write/GroupCommand.cs
- futurenhs.api/FutureNHS.Api/DataAccess/Models/Group/Group.cs
- futurenhs.api/FutureNHS.Api/DataAccess/Models/Group/GroupSummary.cs
- futurenhs.api/FutureNHS.Api/Services/GroupService.cs
- futurenhs.api/FutureNHS.Api/Services/Validation/GroupValidator.cs
- futurenhs.app/form-configs/create-group.ts
- futurenhs.app/form-configs/update-group.ts
- futurenhs.app/services/getGroup/index.ts
- futurenhs.app/services/getGroups/index.ts
[*] Fixes validation message link on group update
> [Api] Renames StrapLine to Strapline

- futurenhs.api/FutureNHS.Api/Controllers/GroupsController.cs
- futurenhs.api/FutureNHS.Api/DataAccess/DTOs/GroupRoleDto.cs
- futurenhs.api/FutureNHS.Api/DataAccess/DTOs/GroupUserDTO.cs
- futurenhs.api/FutureNHS.Api/DataAccess/DTOs/UserDto.cs
- futurenhs.api/FutureNHS.Api/DataAccess/Database/Read/GroupDataProvider.cs
- futurenhs.api/FutureNHS.Api/DataAccess/Database/Write/GroupCommand.cs
- futurenhs.api/FutureNHS.Api/DataAccess/Database/Write/Interfaces/IGroupCommand.cs
- futurenhs.api/FutureNHS.Api/DataAccess/Database/Write/Interfaces/IRolesCommand.cs
- futurenhs.api/FutureNHS.Api/DataAccess/Database/Write/Interfaces/IUserCommand.cs
- futurenhs.api/FutureNHS.Api/DataAccess/Database/Write/RolesCommand.cs
- futurenhs.api/FutureNHS.Api/DataAccess/Database/Write/UserCommand.cs
- futurenhs.api/FutureNHS.Api/DataAccess/Models/Group/GroupMember.cs
- futurenhs.api/FutureNHS.Api/DataAccess/Models/Group/GroupMemberDetails.cs
- futurenhs.api/FutureNHS.Api/Exceptions/ValidationException.cs
- futurenhs.api/FutureNHS.Api/Models/User/Member.cs
- futurenhs.api/FutureNHS.Api/Services/GroupMembershipService.cs
- futurenhs.api/FutureNHS.Api/Services/GroupService.cs
- futurenhs.api/FutureNHS.Api/Services/Interfaces/IGroupMembershipService.cs
[+] Adds endpoint to change group users role
[+] Adds endpoint to delete a group user
> [Api] Story 93481 - Edit group member role

- futurenhs.app/form-configs/create-group.ts
- futurenhs.app/form-configs/update-group.ts
- futurenhs.app/form-configs/update-site-user-role.ts
- futurenhs.app/form-configs/update-site-user.ts
[+] Adds hint for image upload regarding accepted file types and size limit
[*] Amends edit user role label to include 'platform'
> [*] Changes strapline to input field

- futurenhs.automation/features/groupEdit.feature
- futurenhs.automation/features/platformAdmin.feature
[*] strapline step changed to field from text area, 255 character validation
> Group strapline step refactor

- futurenhs.api/FutureNHS.Api/Helpers/BytesToReadable.cs
- futurenhs.api/FutureNHS.Api/Services/Admin/AdminGroupService.cs
- futurenhs.api/FutureNHS.Api/Services/GroupService.cs
- futurenhs.api/FutureNHS.Api/Services/UserService.cs
- futurenhs.api/FutureNHS.Api/Services/Validation/ImageValidator.cs
[*] Changes image upload size to 5MB for create/update group and user profile
> [API] Story 96778 - Image upload size changed to 5MB

- futurenhs.app/components/_pageTemplates/GroupFolderContentsTemplate/index.tsx
> [*] Fixes mobile layout bugs on folder contents grid

- futurenhs.api/FutureNHS.Api/Configuration/GovNotifyConfiguration.cs
- futurenhs.api/FutureNHS.Api/DataAccess/Database/Read/DiscussionsDataProvider.cs
- futurenhs.api/FutureNHS.Api/DataAccess/Database/Read/Interfaces/IDiscussionDataProvider.cs
- futurenhs.api/FutureNHS.Api/DataAccess/Models/Discussions/DiscussionCreatorDetails.cs
- futurenhs.api/FutureNHS.Api/Services/CommentService.cs
- futurenhs.api/FutureNHS.Api/Services/DependencyInjection.cs
- futurenhs.api/FutureNHS.Api/Services/Notifications/CommentNotificationService.cs
- futurenhs.api/FutureNHS.Api/Services/Notifications/Interfaces/ICommentNotificationService.cs
- futurenhs.api/FutureNHS.Api/appsettings.json
[+] Adds notifications for a users comment on a discussion
> [API] Story 94400 - Notifications - Comment on discussion

- futurenhs.automation/features/groupEdit.feature
- futurenhs.automation/pageObjects/formPage.js
- futurenhs.automation/util/helpers.js
[*] refactored form input functions to clearField when setValue = null
> [+] clearField helper

- futurenhs.automation/customCommands.js
- futurenhs.automation/features/groupEdit.feature
- futurenhs.automation/features/groupNavigation.feature
- futurenhs.automation/features/memberProfile.feature
- futurenhs.automation/pageObjects/formPage.js
- futurenhs.automation/pageObjects/loginPage.js
- futurenhs.automation/sqlQueries/dataReset.sql
[*] refactored memberProfile based on changes in sprint
[*] general maintenance of scripts and structure
[*] condition on autoSuggest to allow for '' testing
[+] new 5MB and 5.1MB images for image upload testing.
[*] adjusted login command validation for stability
> Maintenance Commit

- futurenhs.api/FutureNHS.Api/DataAccess/Database/Read/CommentsDataProvider.cs
- futurenhs.api/FutureNHS.Api/DataAccess/Database/Read/DiscussionsDataProvider.cs
- futurenhs.api/FutureNHS.Api/DataAccess/Database/Read/Interfaces/ICommentsDataProvider.cs
- futurenhs.api/FutureNHS.Api/DataAccess/Models/Comment/CommentCreatorDetails.cs
- futurenhs.api/FutureNHS.Api/Services/CommentService.cs
- futurenhs.api/FutureNHS.Api/Services/Notifications/CommentNotificationService.cs
- futurenhs.api/FutureNHS.Api/Services/Notifications/Interfaces/ICommentNotificationService.cs
[+] Adds notifications for a users reply on a comment
> [API] Story 94953 - Notifications - Reply to a comment

- futurenhs.automation/features/platformAdmin.feature
- futurenhs.automation/pageObjects/table.js
- futurenhs.automation/stepDefinitions/ThenSteps.js
[+] new regression test covering altering users platform role
[+] new method for tableRowValidation and accompanying step
> regression coverage, new function

- futurenhs.app/components/ContentBlock/index.tsx
- futurenhs.app/components/ContentBlockManager/index.tsx
- futurenhs.app/components/DataGrid/index.tsx
- futurenhs.app/components/Dialog/index.tsx
- futurenhs.app/components/Dialog/interfaces.ts
- futurenhs.app/components/Form/index.tsx
- futurenhs.app/components/GroupPageHeader/index.tsx
- futurenhs.app/components/Header/index.tsx
- futurenhs.app/components/TabbedNav/index.tsx
- futurenhs.app/components/TabbedNav/interfaces.ts
- futurenhs.app/components/_pageTemplates/GroupFolderContentsTemplate/index.tsx
- futurenhs.app/components/_pageTemplates/GroupMemberUpdateTemplate/index.tsx
- futurenhs.app/content-configs/246485b1-2a13-4844-95d0-1fb401c8fdea.ts
- futurenhs.app/content-configs/3c745d1d-9742-459a-a2bb-7af14c2f291c.ts
- futurenhs.app/content-configs/749bd865-27b8-4af6-960b-3f0458f8e92f.ts
- futurenhs.app/content-configs/8190d347-e29a-4577-baa8-446bcae428d9.ts
- futurenhs.app/content-configs/c0e49c49-f9cb-40c0-bafe-4f603b495b1f.ts
- futurenhs.app/content-configs/c1ffa11a-c06a-4210-96f5-59e9f7f8fff5.ts
- futurenhs.app/pages/404.page.tsx
- futurenhs.app/pages/_app.page.tsx
- futurenhs.app/pages/search/index.page.tsx
- futurenhs.app/services/getGroup/index.ts
- futurenhs.app/services/getGroup/service.test.ts
[+] Sets focus to document.body on route change
[*] Refactor dialog component to fix axe issues - h1, role, labelledby
[+] Adds search term and number of results to search page title
[-] Removes aria-hidden from tables on mobile view
> [*] Replaced all instances of 'Future NHS' with 'FutureNHS'

- futurenhs.api/FutureNHS.Api/Controllers/GroupsController.cs
- futurenhs.api/FutureNHS.Api/DataAccess/Database/Write/GroupCommand.cs
- futurenhs.api/FutureNHS.Api/DataAccess/Database/Write/Interfaces/IGroupCommand.cs
- futurenhs.api/FutureNHS.Api/Models/Member/Request/MemberRequest.cs
- futurenhs.api/FutureNHS.Api/Services/Admin/AdminGroupService.cs
- futurenhs.api/FutureNHS.Api/Services/Admin/Interfaces/IAdminUserService.cs
- futurenhs.api/FutureNHS.Api/Services/GroupMembershipService.cs
- futurenhs.api/FutureNHS.Api/Services/GroupService.cs
- futurenhs.api/FutureNHS.Api/Services/Interfaces/IGroupMembershipService.cs
- futurenhs.api/FutureNHS.Api/Services/Validation/GroupUserApplicationValidator.cs
- futurenhs.app/components/_pageTemplates/GroupMemberListingTemplate/index.tsx
[+] Adds endpoints for accept/reject group user
> [API] Story 72222 - Accept/Reject group user

- futurenhs.api/FutureNHS.Api/DataAccess/DTOs/GroupUserDTO.cs
- futurenhs.api/FutureNHS.Api/DataAccess/Database/Write/GroupCommand.cs
- futurenhs.api/FutureNHS.Api/DataAccess/Database/Write/Interfaces/IGroupCommand.cs
- futurenhs.api/FutureNHS.Api/Services/CommentService.cs
- futurenhs.api/FutureNHS.Api/Services/DependencyInjection.cs
- futurenhs.api/FutureNHS.Api/Services/GroupMembershipService.cs
- futurenhs.api/FutureNHS.Api/Services/Notifications/GroupMembershipNotificationService.cs
- futurenhs.api/FutureNHS.Api/Services/Notifications/Interfaces/IGroupMemberNotificationService.cs
[+] Adds notifications for when a user is accepted/rejected
> [API] Story 83538 - Accept / reject user notification

- futurenhs.api/FutureNHS.Api/DataAccess/Database/Read/GroupDataProvider.cs
- futurenhs.api/FutureNHS.Api/DataAccess/Database/Read/Interfaces/IGroupDataProvider.cs
- futurenhs.api/FutureNHS.Api/Services/GroupMembershipService.cs
- futurenhs.api/FutureNHS.Api/Services/Notifications/CommentNotificationService.cs
- futurenhs.api/FutureNHS.Api/Services/Notifications/GroupMembershipNotificationService.cs
- futurenhs.api/FutureNHS.Api/Services/Notifications/Interfaces/IGroupMemberNotificationService.cs
[+] Adds notification service for groups
> [API] Story 94374 - Admin group notifications

- futurenhs.app/UI/scss/modules/content-block/_content-block.scss
- futurenhs.app/components/ContentBlockManager/index.tsx
- futurenhs.app/components/ContentBlockWrapper/index.tsx
- futurenhs.app/components/Form/index.tsx
- futurenhs.app/components/_contentBlockComponents/KeyLinksBlock/index.tsx
[+] Adds hover style to blocks that are eligible for editing or adding
[*] Improves block focusing handling
> [*] Updates ContentBlockWrapper class naming convention

- futurenhs.automation/features/mobileNavigation.feature
- futurenhs.automation/stepDefinitions/WhenSteps.js
[*] increased mobile regression coverage, general navigation/validation across site.
> Mobile Regression

- futurenhs.data/gulpfile.js
[*] resolving change to deployFutureNHSDatabase including automation data reference
> Removing automation reference in dB deploy gulp

- futurenhs.app/components/ContentBlockManager/index.tsx
- futurenhs.app/components/Pagination/component.test.tsx
- futurenhs.app/components/Pagination/index.tsx
- futurenhs.app/components/_pageLayouts/GroupLayout/component.test.tsx
- futurenhs.app/pages/admin/groups/page.test.tsx
- futurenhs.app/pages/admin/page.test.tsx
- futurenhs.app/pages/admin/users/page.test.tsx
- futurenhs.app/pages/groups/[groupId]/files/[fileId]/detail/page.test.tsx
- futurenhs.app/pages/groups/[groupId]/files/[fileId]/page.test.tsx
- futurenhs.app/pages/groups/[groupId]/folders/[folderId]/page.test.tsx
- futurenhs.app/pages/groups/[groupId]/folders/page.test.tsx
- futurenhs.app/pages/groups/[groupId]/page.test.tsx
- futurenhs.app/pages/groups/page.test.tsx
- futurenhs.content.api/Documentation/FutureNhsContentApi.xml
[*] Fixes null check error on page blocks from API
> [*] Fixes unit tests

- futurenhs.app/components/ContentBlockManager/index.tsx
- futurenhs.app/components/ContentBlockWrapper/index.tsx
- futurenhs.app/components/_formComponents/Input/index.tsx
- futurenhs.app/components/_pageTemplates/GroupHomeTemplate/index.tsx
[*] Fixes inifite loop error caused by trying to gracefully handle non-array props being passed in
[*] Sets maxLength prop on inputs whne maxLength validat or is applied
> [*] Amends ContentBlockManager behaviours following design feedback

- futurenhs.app/components/ContentBlockManager/index.tsx
- futurenhs.app/components/Form/index.tsx
- futurenhs.app/components/_contentBlockComponents/KeyLinksBlock/index.tsx
- futurenhs.app/components/_contentBlockComponents/TextContentBlock/index.tsx
- futurenhs.app/components/_formComponents/Input/index.tsx
- futurenhs.app/components/_formComponents/TextArea/index.tsx
- futurenhs.app/form-configs/content-block-text.ts
[-] Fixes add block button remaining disabled on active block delete
[*] Prevents rendering of block data markup when content property is missing
[+] Adds onBlur listener for final-form to TinyMce instances
> [*] Updates TinyMce toolbar options for text block edit mode

- futurenhs.api/FutureNHS.Api/Controllers/UsersController.cs
- futurenhs.api/FutureNHS.Api/DataAccess/DTOs/UserDto.cs
- futurenhs.api/FutureNHS.Api/DataAccess/Database/Read/Interfaces/IUserDataProvider.cs
- futurenhs.api/FutureNHS.Api/DataAccess/Database/Read/UserDataProvider.cs
- futurenhs.api/FutureNHS.Api/DataAccess/Database/Write/UserCommand.cs
- futurenhs.api/FutureNHS.Api/DataAccess/Models/Group/Group.cs
- futurenhs.api/FutureNHS.Api/DataAccess/Models/User/Member.cs
- futurenhs.api/FutureNHS.Api/DataAccess/Models/User/MemberDetails.cs
- futurenhs.api/FutureNHS.Api/Models/Member/MemberProfile.cs
- futurenhs.api/FutureNHS.Api/Services/GroupMembershipService.cs
- futurenhs.api/FutureNHS.Api/Services/UserService.cs
- futurenhs.api/FutureNHS.Api/Services/Validation/UserValidator.cs
- futurenhs.app/pages/groups/[groupId]/folders/[folderId]/update/index.page.tsx
- futurenhs.app/pages/groups/[groupId]/members/[memberId]/update/index.page.tsx
- futurenhs.app/pages/groups/[groupId]/update/index.page.tsx
- futurenhs.app/pages/users/[userId]/update/index.page.tsx
- futurenhs.app/services/getGroup/index.ts
- futurenhs.app/services/getGroupFolder/index.ts
- futurenhs.app/services/getGroupMember/index.ts
- futurenhs.app/services/getSiteUser/index.ts
[*] Updates getSiteUser to use the new user profile endpoint
contains a fix for one of the issues raised from #208
> [+] Adds new endpoint for getting a users profile

- futurenhs.api/FutureNHS.Api/DataAccess/DTOs/PageDto.cs
- futurenhs.api/FutureNHS.Api/DataAccess/Database/Write/ContentCommand.cs
- futurenhs.api/FutureNHS.Api/DataAccess/Database/Write/Interfaces/IContentCommand.cs
- futurenhs.api/FutureNHS.Api/Services/Admin/AdminGroupService.cs
- futurenhs.api/FutureNHS.Api/Services/ContentService.cs
- futurenhs.content.api/Umbraco9ContentApi.Core/Handlers/FutureNhs/FutureNhsPageHandler.cs
- futurenhs.content.api/Umbraco9ContentApi.Core/Services/FutureNhs/Interface/IFutureNhsContentService.cs
- futurenhs.content.api/Umbraco9ContentApi.Test/Handlers/FutureNhsPageHandlerTests.cs
[+] included unit test that was previously failing
[*] improved naming of variables
> TRY-JW-Include-Unit-Test

- futurenhs.content.api/Umbraco9ContentApi.Core/Handlers/FutureNhs/FutureNhsContentHandler.cs
- futurenhs.content.api/Umbraco9ContentApi.Core/Handlers/FutureNhs/FutureNhsPageHandler.cs
- futurenhs.content.api/Umbraco9ContentApi.Core/Services/FutureNhs/FutureNhsBlockService.cs
- futurenhs.content.api/Umbraco9ContentApi.Core/Services/FutureNhs/FutureNhsContentService.cs
- futurenhs.content.api/Umbraco9ContentApi.Core/Services/FutureNhs/Interface/IFutureNhsBlockService.cs
- futurenhs.content.api/Umbraco9ContentApi.Test/Handlers/FutureNhsContentHandlerTests.cs
This PR is re a bug raised on devtest https://nhsidev.visualstudio.com/FutureNHS%20Open/_workitems/edit/77086
[*] fixed issue where null value was skipping publish logic
[*] improved naming of method
[+] added unit test
> TRY-JW-77086-Editable-Pages-View-published-changes

- futurenhs.api/FutureNHS.Api/DataAccess/Database/Read/GroupDataProvider.cs
[*] altered unused dynamic field returned from GetGroup to determine whether a user is approved, pending approval, or a non member
[*] from a backend perspective, rejected users will still recieve the join permission
> TRY-JW-98659-Pending-Restricted-Group-Request

- futurenhs.app/.storybook/preview.js
- futurenhs.app/components/GroupPageHeader/component.stories.tsx
- futurenhs.app/components/LayoutColumnContainer/component.stories.tsx
- futurenhs.app/components/Loader/component.stories.tsx
[-] Removes unneeded GroupPageHeader story
[*] Adds required missing prop to Loader story
> [+] Adds context into storybook preview to resolve broken stories

- futurenhs.automation/sqlQueries/dataReset.sql
- futurenhs.data/FutureNHS.Data.FutureNHS/dbo/Stored Procedures/AutomationSeed.sql
- futurenhs.data/FutureNHS.Data.FutureNHS/dbo/Stored Procedures/AutomationTeardown.sql
[*] improved groupUser teardown handling in teardown
[*] reduced data management needs for Entity IDs in Teardown and Seed
> Automation Data Script Maintenance

- futurenhs.api/FutureNHS.Api/Controllers/GroupsController.cs
- futurenhs.api/FutureNHS.Api/DataAccess/Database/Read/GroupDataProvider.cs
- futurenhs.api/FutureNHS.Api/DataAccess/Database/Write/GroupCommand.cs
- futurenhs.api/FutureNHS.Api/DataAccess/Models/Group/Group.cs
- futurenhs.api/FutureNHS.Api/DataAccess/Models/Group/GroupSite.cs
- futurenhs.api/FutureNHS.Api/DataAccess/Models/Group/UserGroupPermissions.cs
- futurenhs.api/FutureNHS.Api/Services/GroupMembershipService.cs
- futurenhs.api/FutureNHS.Api/Services/Interfaces/IPermissionsService.cs
- futurenhs.api/FutureNHS.Api/Services/PermissionsService.cs
- futurenhs.api/FutureNHS.Tests/Services/PermissionsServiceTests.cs
- futurenhs.app/components/GroupPageHeader/index.tsx
- futurenhs.app/components/GroupPageHeader/interfaces.ts
- futurenhs.app/components/_pageLayouts/GroupLayout/index.tsx
- futurenhs.app/components/_pageLayouts/GroupLayout/interfaces.ts
- futurenhs.app/constants/group-member-status.ts
- futurenhs.app/hofs/withGroup/index.ts
- futurenhs.app/jest-mocks/handlers.tsx
- futurenhs.app/pages/groups/[groupId]/files/[fileId]/detail/page.test.tsx
- futurenhs.app/pages/groups/[groupId]/files/[fileId]/page.test.tsx
- futurenhs.app/pages/groups/[groupId]/folders/[folderId]/page.test.tsx
- futurenhs.app/pages/groups/[groupId]/folders/page.test.tsx
- futurenhs.app/services/getGroup/index.ts
- futurenhs.app/services/getGroupActions/index.ts
[*] Allows users to join group again after being rejected
> [+] Adds pending approval status/message for private groups

- futurenhs.content.api/Umbraco9ContentApi.Core/Models/Content/ContentModelItemData.cs
- futurenhs.content.api/Umbraco9ContentApi.Core/Resolvers/FutureNHSContentResolver.cs
> TRY-JW-Add-Last-Updated-Prop-To-Content

- futurenhs.app/components/NotificationBanner/index.tsx
- futurenhs.app/components/_pageLayouts/StandardLayout/index.tsx
- futurenhs.app/components/_pageTemplates/GroupHomeTemplate/index.tsx
- futurenhs.app/components/_pageTemplates/GroupMemberInviteTemplate/index.tsx
- futurenhs.app/hooks/useNotification/index.ts
- futurenhs.app/package-lock.json
[+] Adds notification to custom page publish event
> [*] Updates useNotification hook to support clearing of existing queue

- futurenhs.api/FutureNHS.Api/Controllers/CommentController.cs
- futurenhs.api/FutureNHS.Api/Controllers/DiscussionController.cs
- futurenhs.api/FutureNHS.Api/DataAccess/Database/Read/CommentsDataProvider.cs
- futurenhs.api/FutureNHS.Api/DataAccess/Database/Read/DiscussionsDataProvider.cs
- futurenhs.api/FutureNHS.Api/DataAccess/Database/Read/Interfaces/ICommentsDataProvider.cs
- futurenhs.api/FutureNHS.Api/DataAccess/Database/Read/Interfaces/IDiscussionDataProvider.cs
[*] Fixes comment/discussion returned total count
> [Api] Bug 101366 - Incorrect comment/discussion pagination

- futurenhs.app/components/_pageLayouts/StandardLayout/index.tsx
- futurenhs.app/components/_pageTemplates/GroupHomeTemplate/index.tsx
- futurenhs.app/helpers/util/errors/serializeError/index.ts
- futurenhs.app/helpers/util/ssr/handleSSRErrorProps/index.ts
- futurenhs.app/hofs/withGroup/index.ts
- futurenhs.app/hofs/withReset/index.ts
- futurenhs.app/hofs/withUser/index.ts
- futurenhs.app/jest-mocks/handlers.tsx
- futurenhs.app/pages/500.page.tsx
- futurenhs.app/pages/_app.page.tsx
- futurenhs.app/pages/groups/[groupId]/index.page.tsx
- futurenhs.app/services/getCmsPageContent/index.ts
- futurenhs.app/services/getCmsPageTemplate/index.ts
- futurenhs.app/services/getGroup/index.ts
- futurenhs.app/services/getGroupActions/index.ts
- futurenhs.app/services/getGroupHomePageCmsContentIds/index.ts
- futurenhs.app/services/getGroupMember/index.ts
- futurenhs.app/services/getGroups/index.ts
[+] Adds helper to serialise errors for debugging
[+] Adds error debugging data to error page where new env var NEXT_PUBLIC_APP_DEBUG = true
[-] Removes incorrect caching of props.errors between page requests
> [-] Removes confusing logging

- futurenhs.app/components/_formComponents/TextArea/index.tsx
> [*] Strips down RTE toolbar config - GH issue #241

- futurenhs.app/components/_pageTemplates/GroupFileDetailTemplate/index.tsx
> [*] Fixes mobile layout bug on GroupFileDetails template/table

- futurenhs.api/FutureNHS.Api/DataAccess/Database/Write/GroupCommand.cs
[+] Adds group owners as group admins
> [Api] Bug 99548 - Group owners not automatically group admins

- futurenhs.automation/customCommands.js
- futurenhs.automation/features/editablePagesValidation.feature
- futurenhs.automation/features/groupEdit.feature
- futurenhs.automation/features/groupPrivate.feature
- futurenhs.automation/features/platformAdmin.feature
- futurenhs.automation/pageObjects/editablePages.js
- futurenhs.automation/pageObjects/formPage.js
- futurenhs.automation/stepDefinitions/ThenSteps.js
- futurenhs.automation/stepDefinitions/WhenSteps.js
- futurenhs.automation/util/helpers.js
Resolved spelling error
Formatting for readability/consistency
Improved function handling on error to wait
Programmatic instance finding of form fields
> Sprint 5 Week 1 Maintenance

- futurenhs.automation/features/fed.feature
- futurenhs.automation/features/filesManagement.feature
- futurenhs.automation/features/foldersManagement.feature
- futurenhs.automation/features/groupMembers.feature
- futurenhs.automation/features/groupNavigation.feature
- futurenhs.automation/features/groupPrivate.feature
- futurenhs.automation/features/groupPublic.feature
- futurenhs.automation/features/mobileNavigation.feature
- futurenhs.automation/features/userAccess.feature
- futurenhs.automation/pageObjects/filesPage.js
- futurenhs.automation/pageObjects/genericPage.js
Minor script changes
Refactored dialog select for new Join/Leave group POST functionality
Resolved selector issue with Download file link
> End of Sprint - Regression Maintenance

- futurenhs.app/content-configs/578dfcc6-857f-4eda-8779-1d9b110888c7.ts
- futurenhs.app/form-configs/create-group.ts
- futurenhs.app/form-configs/update-group.ts
> Inconsistency between naming colour theme or theme colour #337

- futurenhs.app/components/Header/index.tsx
Fix screen reader text on search bar
> Wrong screen reader text on search bar #336

- futurenhs.app/components/_pageTemplates/GroupDiscussionTemplate/index.tsx
> Clearer discussion posts #351

- futurenhs.app/content-configs/46524db4-44eb-4296-964d-69dfc2279f01.ts
Updated register interest link so it points to a MS Form rather than an email address.
Also added a class so that we can track clicks through Google Tag Manager
> Update register interest link

- futurenhs.app/services/getSiteUsersByTerm/index.ts
> Showing the users email address next to their name issue #360

- futurenhs.app/assets/icons/arrow-up.svg
- futurenhs.app/components/forms/Form/index.tsx
- futurenhs.app/components/forms/Form/interfaces.ts
- futurenhs.app/pages/groups/[groupId]/forum/[discussionId]/index.page.tsx
- Show back to top icon if there is more than two comments in the discussion.
> Add 'back to top ' icon at bottom of page #367
